[package]
name = "user_auth_wasm"
version = "0.1.0"
edition = "2021"

[dependencies]
argon2 = "0.5.3"
getrandom = { version = "0.2.15", features = ["js"] }
wasm-bindgen = "0.2.100"

[lib]
crate-type = ["cdylib", "rlib"]
